"""Generate the reproducible Cliente-Pedido sprint 8 artifact, without starting services."""
from pathlib import Path
import sys
from io import BytesIO
from zipfile import ZipFile
import json
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app.schemas.uml import UMLCanvasDiagram
from app.services.generator.packager import generate_spring


if __name__ == '__main__':
    root = Path(__file__).resolve().parents[2]
    diagram = UMLCanvasDiagram.model_validate_json((root / 'exports/cliente-pedido.json').read_text(encoding='utf-8'))
    raw, _ = generate_spring(diagram)
    target = root / 'exports/sprint-8-cliente-pedido'
    with ZipFile(BytesIO(raw)) as archive:
        # Only paths generated by our packager, never an uploaded ZIP.
        archive.extractall(target)
        contract = archive.read('mobile-contract.json')
    expected = root / 'mobile/assets/mobile-contract.json'
    if json.loads(expected.read_text(encoding='utf-8')) != json.loads(contract):
        raise SystemExit('Descriptor mobile distinto. Revise el cambio del modelo antes de actualizar el asset.')
    (root / 'exports/sprint-8-cliente-pedido.zip').write_bytes(raw)
    print(target)
